
services:
  nginx:
    image: nginx:stable-bookworm
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    expose:
      - "9000"
    volumes:
      - ./server:/var/www 