services:
  nginx:
    image: nginx:stable-bookworm
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    expose:
      - "9000"
    volumes:
      - ./server:/var/www 
    networks:
      - app-network

  frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: sh -c 'cd app && npm run start'
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
